version: '3.3'
# docker run --hostname msgrelay --name msgrelay --rm -p 6000:6000 -p 5555:5555  -t msgrelay
# docker run  --name worker --rm --link=msgrelay -v /var/run/docker.sock:/var/run/docker.sock  -t worker
#
services:
  msgreply:
    image: msgrelay
    container_name: msgrelay
    hostname: msgrelay
    ports:
    - "6000:6000"
  worker:
    image: worker
    #deploy:
    #  mode: replicated
    #  replicas: 2 
    #container_name: worker
    #hostname: worker
    links:
      - msgreply
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
